### ISSUE TITLE
Wastewater charges 

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/Open-Water-Rate-Specification#486]
One noted enhancement of OWRS would be to add in wastewater rates. Chris what are your thoughts on how to incorporate? 

Thinking this would be a separate section of each OWRS file that follows the same fixed / volumetric breakdown. 

In terms of existing data sources, the Water Boards collects and issue the annual Wastewater User Charge Survey Report

https://www.waterboards.ca.gov/water_issues/programs/grants_loans/srf/docs/fy1617/fy1617ww_user_charge_survey.pdf

And here you may find those reports since 1996-97

https://www.waterboards.ca.gov/publications_forms/publications/general/#Ww

Also worth looking at EPAs clean watersheds Needs Survey that assess the capital investment needed for publicly-owned wastewater collection and treatment facilities to meet the water quality goals of the Clean Water Act.

https://www.epa.gov/cwns

h/t RM

**Comment by christophertull** [comment]
So this is something we actually support more-or-less already, but it is not documented in the OWRS repo and we didn't emphasize it during data collection. I think we may have commented out the sections of the survey that collect WW rate info before sending out it out last year.

The basic approach just adds additional sections that append `_wastewater` like below:

```yaml
FIRE_SERVICE:
    service_charge:
      depends_on:
        - meter_size
      values:
        1": 7.63
        2": 7.63
        3": 22.15
        4": 47.19
        6": 137.08
        8": 292.11
        10": 525.31
        12": 848.52
    commodity_charge: flat_rate_commodity*usage_ccf
    flat_rate_commodity: 0
    fixed_drought_surcharge: 0
    variable_drought_surcharge: 0
    fixed_wastewater_charge: 0
    variable_wastewater_charge: 0
    bill: service_charge+commodity_charge 
```

Then the bill calculation would need to become 
```yaml
bill: service_charge+commodity_charge+fixed_wastewater_charge+variable_wastewater_charge
```

In terms of todos, mainly seems like
- [ ] Document this in the README
- [ ] Peruse the references listed to make sure the `rateparser` supports most common types of WW rates.
- [ ] Test with the survey and make sure everything is actually working the way I think it works.
