### ISSUE TITLE
MVWD "domestic" water use

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/Open-Water-Rate-Specification#5]
Should ask folks at MVWD whether "domestic" water aligns with our POTABLE classification.

```yaml
rate:
  depends_on: water_type
  values:
    domestic: 2.39
    recycled: 1.96
```
